---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    force: "${GALAXY_FORCE:-true}"
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: podman
platforms:
  - name: "github_cli-${image:-debian}-${tag:-latest}${TOX_ENVNAME}"
    image: "quay.io/gotmax23/${image:-debian}-systemd:${tag:-latest}"
    command: ""
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: "../playbooks/${CONVERGE_PLAYBOOK:-converge.yml}"
    prepare: "../playbooks/${PREPARE_PLAYBOOK:-prepare.yml}"
    verify: "../playbooks/${VERIFY_PLAYBOOK:-verify.yml}"
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
