---
- name: Converge
  hosts: all
  become: true

  vars:
    github_cli_state: "{{ lookup('env', 'github_cli_state') | default('present', True) }}"

  tasks:
    - name: Install Github CLI
      ansible.builtin.include_role:
        name: "gotmax23.github_cli"
