---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Install Github CLI
      vars:
        github_cli_state: present
      ansible.builtin.include_role:
        name: "gotmax23.github_cli"
