---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure which is installed (needed for verify)
      when: ansible_os_family != "Debian"
      ansible.builtin.package:
        name: which
