---
- name: Verify
  hosts: all

  vars:
    github_cli_state: "{{ lookup('env', 'github_cli_state') | default('present', True) }}"

  tasks:
    - name: Check if Github CLI is present
      register: github_cli_presence
      changed_when: false
      failed_when: false
      ansible.builtin.command:
        cmd: which gh

    - name: Ensure Pass is installed
      when: github_cli_state == "present"
      ansible.builtin.assert:
        quiet: true
        that: github_cli_presence == 0


    - name: Ensure Pass is uninstalled
      when: github_cli_state == "absent"
      ansible.builtin.assert:
        quiet: true
        that: github_cli_presence != 0
