---
#
# Ansible managed
#
name: Lint code and run Molecule tests

'on':
  push:
    paths-ignore:
      - README.md
      - .github/settings.yml
  pull_request:
    paths-ignore:
      - README.md
      - .github/settings.yml
  workflow_dispatch:
  schedule:
    - cron: "15 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Generate cache keys
        id: keys
        run: |
          echo ::set-output name=pip_cache_dir::$(pip cache dir)
          echo ::set-output name=date::$(date +%Y_%g)

      - name: Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.keys.outputs.pip_cache_dir }}
          key: ansible-pip-${{ steps.keys.outputs.date }}

      - name: Install pip packages
        run: |
          pip3 install -U pip
          pip3 install wheel
          pip3 install molecule molecule-podman ansible-core yamllint ansible-lint

      # This is necessary to allow running systemd in rootless containers.
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1

      - name: Set necessary sysctls for running multiple Systemd containers.
        run: |
          sudo sysctl -w fs.inotify.max_queued_events=204800
          sudo sysctl -w fs.inotify.max_user_instances=204800
          sudo sysctl -w fs.inotify.max_user_watches=204800

      - name: Run molecule test
        run: |
          ansible-galaxy collection install containers.podman
          molecule test -s all
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
